# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = mega2560
ARDUINO_LIBS = EscapeControl SoftwareSerial
USER_LIB_PATH = ../../../
OBJDIR = build

include /usr/share/arduino/Arduino.mk
